---
apiVersion: v1
kind: Template
name: uhc-acct-mangr-routes
metadata:
  name: route

objects:

- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: brontosaurus
    labels:
      app: brontosaurus
  spec:
    host: brontosaurus.apps-crc.testing
    to:
      kind: Service
      name: brontosaurus
    tls:
      termination: reencrypt
      insecureEdgeTerminationPolicy: Redirect
